#\!/usr/bin/env bash
# ccs-handoff.sh — Session handoff and resume prompt generation
# Sourced by ccs-dashboard.sh — do not source directly

# ── ccs-handoff [project-dir] — generate session handoff note ──
ccs-handoff() {
  if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    cat <<'HELP'
ccs-handoff [project-dir]  — generate session handoff note (default: current dir)
[personal tool, not official Claude Code]

Generates a markdown handoff file with auto-filled:
  - Open sessions summary
  - Filtered conversation pairs (user + Claude, skips meta)
  - Git state (branch, commits, uncommitted)
  - Recent file operations (Read/Edit/Write/Bash)
  - TodoWrite task progress (if any)
  - Bootstrap prompt (for pasting into new session)

Output: ~/docs/tmp/handoff/<date>-<topic-slug>.md

Options:
  -n COUNT    Number of conversation pairs to include (default: 5)
  --no-prompt Skip appending bootstrap prompt section
HELP
    return 0
  fi

  local project_dir="" pair_count=5 include_prompt=true
  while [ $# -gt 0 ]; do
    case "$1" in
      -n) pair_count="$2"; shift 2 ;;
      --no-prompt) include_prompt=false; shift ;;
      --*) echo "Unknown option: $1" >&2; return 1 ;;
      *) project_dir="$1"; shift ;;
    esac
  done
  [ -z "$project_dir" ] && project_dir="."
  project_dir=$(cd "$project_dir" && pwd)
  local projects_dir="$HOME/.claude/projects"
  local handoff_dir="$HOME/docs/tmp/handoff"
  mkdir -p "$handoff_dir"

  # Find matching project dir in .claude/projects (fuzzy match)
  local encoded_dir
  encoded_dir=$(_ccs_find_project_dir "$project_dir") || {
    echo "No Claude sessions found for: $project_dir"
    return 1
  }
  local session_dir="$projects_dir/$encoded_dir"

  # Collect open (non-archived) sessions from last 7 days, sorted by recency
  local open_sessions=()
  while IFS=$'\t' read -r _ path; do
    open_sessions+=("$path")
  done < <(
    find "$session_dir" -maxdepth 1 \( -name "*.jsonl" -o -name "*.json" \) -mmin -10080 ! -path "*/subagents/*" -print0 2>/dev/null \
    | while IFS= read -r -d '' f; do
        _ccs_is_archived "$f" && continue
        printf '%s\t%s\n' "$(stat -c '%Y' "$f")" "$f"
      done | sort -rn
  )

  if [ ${#open_sessions[@]} -eq 0 ]; then
    echo "No open sessions found for: $project_dir"
    return 1
  fi

  # Extract info from the most recent open session
  local latest="${open_sessions[0]}"
  local full_sid sid mod_date topic

  full_sid=$(basename "$latest" | sed -e 's/\.jsonl$//' -e 's/\.json$//')
  sid=$(echo "$full_sid" | cut -c1-8)
  mod_date=$(stat -c "%y" "$latest" | cut -d. -f1)

  topic=$(_ccs_topic_from_jsonl "$latest")
  [ -z "$topic" ] && topic="(no topic)"

  # Git context
  local git_branch git_status git_log
  git_branch=$(cd "$project_dir" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "N/A")
  git_status=$(cd "$project_dir" && git status --short 2>/dev/null | head -10)
  git_log=$(cd "$project_dir" && git log --oneline -5 2>/dev/null)

  # Conversation summary (filtered, with Claude responses)
  local conversation_md
  conversation_md=$(_ccs_conversation_md "$latest" "$pair_count")

  # Recent file operations
  local recent_files
  recent_files=$(_ccs_recent_files_md "$latest")

  # TodoWrite progress
  local todos
  todos=$(_ccs_todos_md "$latest")

  # All open sessions summary
  local sessions_summary=""
  local zombie_count=0
  for f in "${open_sessions[@]}"; do
    local s_sid s_mod s_ago s_age s_topic
    s_sid=$(basename "$f" | sed -e 's/\.jsonl$//' -e 's/\.json$//' | cut -c1-8)
    s_mod=$(stat -c "%Y" "$f"); s_ago=$(( ($(date +%s) - s_mod) / 60 ))
    if [ "$s_ago" -lt 60 ]; then s_age="${s_ago}m"
    elif [ "$s_ago" -lt 1440 ]; then s_age="$((s_ago/60))h"
    else s_age="$((s_ago/1440))d"; fi
    s_topic=$(_ccs_topic_from_jsonl "$f")
    if [ "$s_topic" = "-" ] || echo "$s_topic" | grep -q '^<'; then
      zombie_count=$((zombie_count + 1))
      continue
    fi
    sessions_summary="${sessions_summary}| \`${s_sid}\` | ${s_age} ago | ${s_topic} |
"
  done
  [ "$zombie_count" -gt 0 ] && sessions_summary="${sessions_summary}
*+ ${zombie_count} zombie sessions (no topic/system-only)*
"

  # Generate slug for filename
  local slug
  slug=$(echo "$topic" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/-/g; s/--*/-/g; s/^-//; s/-$//' | cut -c1-40)
  [ -z "$slug" ] && slug="handoff"
  local handoff_file="$handoff_dir/$(date '+%Y-%m-%d')-${slug}.md"

  cat > "$handoff_file" << EOF
# 交接：${topic}

> Auto-generated by \`ccs-handoff\` — $(date '+%Y-%m-%d %H:%M')
> Project: \`${project_dir}\`

## Open Sessions

| Session ID | Last Active | Topic |
|------------|-------------|-------|
${sessions_summary}
## 對話脈絡

**Session:** \`${sid}\` | **Branch:** \`${git_branch}\` | **Last Active:** ${mod_date}

${conversation_md}
## Git 狀態

\`\`\`
Branch: ${git_branch}

Recent commits:
${git_log:-"(no commits)"}

Uncommitted:
${git_status:-"(clean)"}
\`\`\`
EOF

  # Recent files section (only if non-empty)
  if [ -n "$recent_files" ]; then
    cat >> "$handoff_file" << EOF

## 最近操作的檔案

\`\`\`
${recent_files}
\`\`\`
EOF
  fi

  # TodoWrite progress (only if non-empty)
  if [ -n "$todos" ]; then
    cat >> "$handoff_file" << EOF

## 任務進度（TodoWrite）

${todos}
EOF
  fi

  # Manual sections
  cat >> "$handoff_file" << 'EOF'

## 目前進度

<!-- 補充自動摘要未涵蓋的部分 -->
-

## 下一步

<!-- 下一個 session 應該做什麼 -->
-

## 重要決策

<!-- 這個 session 做了哪些重要決策，為什麼 -->
-
EOF

  # Bootstrap prompt section
  if $include_prompt; then
    local bootstrap
    bootstrap=$(ccs-resume-prompt "$sid" --stdout 2>/dev/null)
    if [ -n "$bootstrap" ]; then
      cat >> "$handoff_file" << EOF

## Bootstrap Prompt

> 直接貼入新 session 即可接手。也可以用 \`ccs-resume-prompt ${sid} --copy\` 複製。

\`\`\`markdown
${bootstrap}
\`\`\`
EOF
    fi
  fi

  echo "Created: $handoff_file"
  echo ""
  echo "  Topic:    ${topic}"
  echo "  Sessions: ${#open_sessions[@]} open"
  echo "  Branch:   ${git_branch}"
  [ -n "$todos" ] && echo "  Tasks:    $(echo "$todos" | wc -l) items"
  [ -n "$recent_files" ] && echo "  Files:    $(echo "$recent_files" | wc -l) operations"
  echo ""
  echo "Edit the file to fill in: 目前進度 / 下一步 / 重要決策"
}

# ── ccs-resume-prompt [session-id-prefix] — generate bootstrap prompt for new session ──
ccs-resume-prompt() {
  if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    cat <<'HELP'
ccs-resume-prompt [session-id-prefix]  — generate bootstrap prompt for new session
[personal tool, not official Claude Code]

Generates a concise bootstrap prompt (< 2000 tokens) from an existing session,
designed to paste into a fresh Claude Code session for seamless handoff.

Arguments:
  session-id-prefix   First N chars of session UUID (from ccs-active/ccs-sessions)
                      If omitted, uses the most recent session in current project dir.

Options:
  -a, --all           Search all projects (not just current dir)
  -n COUNT            Number of recent prompt-response pairs to summarize (default: 3)
  --copy              Copy to clipboard (xclip)
  --stdout            Print raw prompt only (no header/footer, for piping)
HELP
    return 0
  fi

  local prefix="" search_all=false pair_count=3 do_copy=false raw=false
  while [ $# -gt 0 ]; do
    case "$1" in
      -a|--all) search_all=true; shift ;;
      -n) pair_count="$2"; shift 2 ;;
      --copy) do_copy=true; shift ;;
      --stdout) raw=true; shift ;;
      *) prefix="$1"; shift ;;
    esac
  done

  local jsonl
  jsonl=$(_ccs_resolve_jsonl "$prefix" "$search_all")
  if [ -z "$jsonl" ]; then
    if [ -n "$prefix" ]; then
      echo "No session found matching: ${prefix}*" >&2
    else
      echo "No sessions for current dir. Use -a to search all, or provide a session ID prefix." >&2
    fi
    return 1
  fi

  # ── Session metadata ──
  local full_sid sid topic dir project project_dir
  full_sid=$(basename "$jsonl" | sed -e 's/\.jsonl$//' -e 's/\.json$//')
  sid=$(echo "$full_sid" | cut -c1-8)
  topic=$(_ccs_topic_from_jsonl "$jsonl")

  dir=$(basename "$(dirname "$jsonl")")
  project=$(echo "$dir" | sed "s/^${_CCS_HOME_ENCODED}-*//; s/-/\//g")
  [ -z "$project" ] && project="~(home)"
  # Reconstruct project_dir from encoded dir name
  project_dir=$(_ccs_resolve_project_path "$dir" 2>/dev/null)
  [ ! -d "$project_dir" ] && project_dir=""

  # ── Git context (if project dir exists) ──
  local git_branch="" git_status="" git_log=""
  if [ -n "$project_dir" ] && [ -d "$project_dir/.git" ]; then
    git_branch=$(cd "$project_dir" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "N/A")
    git_status=$(cd "$project_dir" && git status --short 2>/dev/null | head -5)
    git_log=$(cd "$project_dir" && git log --oneline -3 2>/dev/null)
  fi

  # ── Extract recent conversation pairs ──
  # Count only real user prompts (skip meta/system messages)
  # Build filtered pair indices: map real prompt index → raw prompt index
  local -a real_to_raw=()
  local raw_idx=0
  while IFS=$'\t' read -r is_meta content; do
    raw_idx=$((raw_idx + 1))
    # Skip meta messages (isMeta flag from Claude)
    [ "$is_meta" = "true" ] && continue
    # Skip system/command wrapper messages
    case "$content" in
      '<local-command'*|'<command-name'*|'<system-'*) continue ;;
    esac
    # Skip /exit, /quit, empty
    [[ "$content" =~ ^[[:space:]]*/exit ]] && continue
    [[ "$content" =~ ^[[:space:]]*/quit ]] && continue
    [ -z "${content// /}" ] && continue
    real_to_raw+=("$raw_idx")
  local provider=$(_ccs_get_provider "$jsonl")
  done < <(
    if [ "$provider" = "gemini" ]; then
      jq -c ".[]" "$jsonl" 2>/dev/null
    else
      cat "$jsonl" 2>/dev/null
    fi | jq -r '
      select(.type == "user" and (.message.content | type == "string")) |
      [(.isMeta // false | tostring), (.message.content | .[:80] | gsub("\n"; " "))] |
      @tsv
    ' 2>/dev/null
  )

  local real_count=${#real_to_raw[@]}
  local start_from=$((real_count - pair_count + 1))
  [ "$start_from" -lt 1 ] && start_from=1

  local conversation_summary=""
  local ri
  for ((ri = start_from; ri <= real_count; ri++)); do
    local raw_p=${real_to_raw[$((ri - 1))]}
    local pair_json user_text assistant_text user_preview assistant_preview
    pair_json=$(_ccs_get_pair "$jsonl" "$raw_p")
    user_text=$(echo "$pair_json" | head -1 | jq -r '.text' 2>/dev/null)
    assistant_text=$(echo "$pair_json" | tail -1 | jq -r '.text' 2>/dev/null)

    # Truncate for token efficiency
    user_preview=$(echo "$user_text" | head -3 | cut -c1-200)
    local user_lines
    user_lines=$(echo "$user_text" | wc -l)
    [ "$user_lines" -gt 3 ] && user_preview="${user_preview}..."

    assistant_preview=$(echo "$assistant_text" | head -5 | cut -c1-200)
    local asst_lines
    asst_lines=$(echo "$assistant_text" | wc -l)
    [ "$asst_lines" -gt 5 ] && assistant_preview="${assistant_preview}..."

    conversation_summary="${conversation_summary}
### [${ri}/${real_count}] User
${user_preview}

### [${ri}/${real_count}] Claude
${assistant_preview}
"
  done

  # ── Extract tool usage from last assistant turn ──
  local recent_files=""
  local jq_recent_filter='select(.type == "assistant") | .message.content[]? | select(.type == "tool_use") | if .name == "Read" then "R " + .input.file_path elif .name == "Edit" then "E " + .input.file_path elif .name == "Write" then "W " + .input.file_path elif .name == "Bash" then "$ " + (.input.command | split("\n") | first | .[:80]) else empty end'
  recent_files=$( (
    if [ "$provider" = "gemini" ]; then
      jq -c ".[]" "$jsonl" 2>/dev/null
    else
      cat "$jsonl" 2>/dev/null
    fi
  ) | jq -r "$jq_recent_filter" 2>/dev/null | tail -10 | sort -u)

  # ── Build the prompt ──
  local prompt=""
  read -r -d '' prompt << PROMPT_EOF
繼續上一個 session 的工作：**${topic}**

## Context

- **Project:** ${project}
- **Session:** \`${sid}\` (${real_count} prompts)$(
[ -n "$git_branch" ] && printf '\n- **Branch:** `%s`' "$git_branch"
)$(
[ -n "$git_log" ] && printf '\n- **Recent commits:**\n```\n%s\n```' "$git_log"
)$(
[ -n "$git_status" ] && printf '\n- **Uncommitted changes:**\n```\n%s\n```' "$git_status"
[ -z "$git_status" ] && [ -n "$git_branch" ] && printf '\n- **Working tree:** clean'
)

## 最近對話摘要
${conversation_summary}$(
[ -n "$recent_files" ] && printf '\n## 最近操作的檔案\n\n```\n%s\n```' "$recent_files"
)

## Instructions

請先確認你理解上述 context，然後繼續未完成的工作。如果需要更多資訊，先讀取相關檔案再動手。
PROMPT_EOF

  # ── Output ──
  if $raw; then
    echo "$prompt"
  else
    if ! $do_copy; then
      printf "\033[1;36m━━ Resume Prompt ━━\033[0m  \033[90m%s | %s | %d prompts\033[0m\n\n" "$sid" "$topic" "$real_count"
    fi
    echo "$prompt"
    if ! $do_copy; then
      echo
      printf "\033[90m---\033[0m\n"
      printf "\033[90mPaste the above into a new session, or use:\033[0m\n"
      printf "\033[33m  ccs-resume-prompt %s --copy     \033[90m# copy to clipboard\033[0m\n" "$sid"
      local provider=$(_ccs_get_provider "$jsonl")
      if [ "$provider" = "gemini" ]; then
        printf "\033[33m  gemini --session %s  \033[90m# resume with full context (heavier)\033[0m\n" "$full_sid"
      else
        printf "\033[33m  claude --resume %s  \033[90m# resume with full context (heavier)\033[0m\n" "$full_sid"
      fi
    fi
  fi

  # ── Copy to clipboard ──
  if $do_copy; then
    if command -v xclip &>/dev/null; then
      echo "$prompt" | xclip -selection clipboard
      printf "\033[32mCopied to clipboard!\033[0m (%d chars)\n" "${#prompt}" >&2
    elif command -v xsel &>/dev/null; then
      echo "$prompt" | xsel --clipboard --input
      printf "\033[32mCopied to clipboard!\033[0m (%d chars)\n" "${#prompt}" >&2
    else
      echo "No clipboard tool found (install xclip or xsel)" >&2
      echo "$prompt"
    fi
  fi
}

